# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c78cf69604983d2eb70262f2424740ae4c452ee247889a401dc82796624fe78941e9e47260af45067ee216466bc545b077fc507ab17994a813fbd5cd8b371d1f

test:
  secret_key_base: 5ac91c51b7673e0c0b850257c265ab13fe968c099dfe2a53f88dc8a6a0d84ce24626669f3909cf89a4c7d06d31b428be1434191235e0db6b928b73f38b3e062e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
